package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1



/**
 * AwardsAchive generated by hbm2java
 */
public class AwardsAchive  implements java.io.Serializable {


     private Integer idAwards;
     private String award;
     private String studentNic;

    public AwardsAchive() {
    }

    public AwardsAchive(String award, String studentNic) {
       this.award = award;
       this.studentNic = studentNic;
    }
   
    public Integer getIdAwards() {
        return this.idAwards;
    }
    
    public void setIdAwards(Integer idAwards) {
        this.idAwards = idAwards;
    }
    public String getAward() {
        return this.award;
    }
    
    public void setAward(String award) {
        this.award = award;
    }
    public String getStudentNic() {
        return this.studentNic;
    }
    
    public void setStudentNic(String studentNic) {
        this.studentNic = studentNic;
    }




}


