package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EducationalLevel generated by hbm2java
 */
public class EducationalLevel  implements java.io.Serializable {


     private Integer idEdu;
     private String levelName;
     private Set students = new HashSet(0);

    public EducationalLevel() {
    }

    public EducationalLevel(String levelName, Set students) {
       this.levelName = levelName;
       this.students = students;
    }
   
    public Integer getIdEdu() {
        return this.idEdu;
    }
    
    public void setIdEdu(Integer idEdu) {
        this.idEdu = idEdu;
    }
    public String getLevelName() {
        return this.levelName;
    }
    
    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


