package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fields generated by hbm2java
 */
public class Fields  implements java.io.Serializable {


     private Integer idfields;
     private String fieldName;
     private Set students = new HashSet(0);

    public Fields() {
    }

    public Fields(String fieldName, Set students) {
       this.fieldName = fieldName;
       this.students = students;
    }
   
    public Integer getIdfields() {
        return this.idfields;
    }
    
    public void setIdfields(Integer idfields) {
        this.idfields = idfields;
    }
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


