package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1



/**
 * FileAtttach generated by hbm2java
 */
public class FileAtttach  implements java.io.Serializable {


     private Integer idfileAtttach;
     private Student student;
     private String photo;
     private String cv;
     private int studentIdstudent;

    public FileAtttach() {
    }

	
    public FileAtttach(Student student, int studentIdstudent) {
        this.student = student;
        this.studentIdstudent = studentIdstudent;
    }
    public FileAtttach(Student student, String photo, String cv, int studentIdstudent) {
       this.student = student;
       this.photo = photo;
       this.cv = cv;
       this.studentIdstudent = studentIdstudent;
    }
   
    public Integer getIdfileAtttach() {
        return this.idfileAtttach;
    }
    
    public void setIdfileAtttach(Integer idfileAtttach) {
        this.idfileAtttach = idfileAtttach;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }
    public int getStudentIdstudent() {
        return this.studentIdstudent;
    }
    
    public void setStudentIdstudent(int studentIdstudent) {
        this.studentIdstudent = studentIdstudent;
    }




}


