package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer idpaymt;
     private Status status;
     private String nic;
     private String tpNo;
     private int studentIdstudent;
     private Set students = new HashSet(0);

    public Payment() {
    }

	
    public Payment(String nic, int studentIdstudent) {
        this.nic = nic;
        this.studentIdstudent = studentIdstudent;
    }
    public Payment(Status status, String nic, String tpNo, int studentIdstudent, Set students) {
       this.status = status;
       this.nic = nic;
       this.tpNo = tpNo;
       this.studentIdstudent = studentIdstudent;
       this.students = students;
    }
   
    public Integer getIdpaymt() {
        return this.idpaymt;
    }
    
    public void setIdpaymt(Integer idpaymt) {
        this.idpaymt = idpaymt;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getTpNo() {
        return this.tpNo;
    }
    
    public void setTpNo(String tpNo) {
        this.tpNo = tpNo;
    }
    public int getStudentIdstudent() {
        return this.studentIdstudent;
    }
    
    public void setStudentIdstudent(int studentIdstudent) {
        this.studentIdstudent = studentIdstudent;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


