package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Qualification generated by hbm2java
 */
public class Qualification  implements java.io.Serializable {


     private Integer idqua;
     private String proQua;
     private String awardsAchiv;
     private String studentNic;
     private Set students = new HashSet(0);

    public Qualification() {
    }

    public Qualification(String proQua, String awardsAchiv, String studentNic, Set students) {
       this.proQua = proQua;
       this.awardsAchiv = awardsAchiv;
       this.studentNic = studentNic;
       this.students = students;
    }
   
    public Integer getIdqua() {
        return this.idqua;
    }
    
    public void setIdqua(Integer idqua) {
        this.idqua = idqua;
    }
    public String getProQua() {
        return this.proQua;
    }
    
    public void setProQua(String proQua) {
        this.proQua = proQua;
    }
    public String getAwardsAchiv() {
        return this.awardsAchiv;
    }
    
    public void setAwardsAchiv(String awardsAchiv) {
        this.awardsAchiv = awardsAchiv;
    }
    public String getStudentNic() {
        return this.studentNic;
    }
    
    public void setStudentNic(String studentNic) {
        this.studentNic = studentNic;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


