package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1



/**
 * Reference generated by hbm2java
 */
public class Reference  implements java.io.Serializable {


     private Integer idrefer;
     private Student student;
     private String refName;
     private String refPost;
     private String address;
     private String email;
     private String conNo;
     private String refNo;

    public Reference() {
    }

    public Reference(Student student, String refName, String refPost, String address, String email, String conNo, String refNo) {
       this.student = student;
       this.refName = refName;
       this.refPost = refPost;
       this.address = address;
       this.email = email;
       this.conNo = conNo;
       this.refNo = refNo;
    }
   
    public Integer getIdrefer() {
        return this.idrefer;
    }
    
    public void setIdrefer(Integer idrefer) {
        this.idrefer = idrefer;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getRefName() {
        return this.refName;
    }
    
    public void setRefName(String refName) {
        this.refName = refName;
    }
    public String getRefPost() {
        return this.refPost;
    }
    
    public void setRefPost(String refPost) {
        this.refPost = refPost;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getConNo() {
        return this.conNo;
    }
    
    public void setConNo(String conNo) {
        this.conNo = conNo;
    }
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }




}


