package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer idstatus;
     private Boolean status;
     private Set payments = new HashSet(0);

    public Status() {
    }

    public Status(Boolean status, Set payments) {
       this.status = status;
       this.payments = payments;
    }
   
    public Integer getIdstatus() {
        return this.idstatus;
    }
    
    public void setIdstatus(Integer idstatus) {
        this.idstatus = idstatus;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }




}


