package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String nic;
     private Branch branch;
     private Duration duration;
     private EducationalLevel educationalLevel;
     private Fields fields;
     private Payment payment;
     private Qualification qualification;
     private University university;
     private String name;
     private String fullname;
     private String gender;
     private Date dob;
     private String address;
     private String tpNo;
     private String refNo;
     private String email;
     private Date dor;
     private String al;
     private String ol;
     private Set logins = new HashSet(0);
     private Set fileAtttaches = new HashSet(0);
     private Set references = new HashSet(0);

    public Student() {
    }

	
    public Student(String nic) {
        this.nic = nic;
    }
    public Student(String nic, Branch branch, Duration duration, EducationalLevel educationalLevel, Fields fields, Payment payment, Qualification qualification, University university, String name, String fullname, String gender, Date dob, String address, String tpNo, String refNo, String email, Date dor, String al, String ol, Set logins, Set fileAtttaches, Set references) {
       this.nic = nic;
       this.branch = branch;
       this.duration = duration;
       this.educationalLevel = educationalLevel;
       this.fields = fields;
       this.payment = payment;
       this.qualification = qualification;
       this.university = university;
       this.name = name;
       this.fullname = fullname;
       this.gender = gender;
       this.dob = dob;
       this.address = address;
       this.tpNo = tpNo;
       this.refNo = refNo;
       this.email = email;
       this.dor = dor;
       this.al = al;
       this.ol = ol;
       this.logins = logins;
       this.fileAtttaches = fileAtttaches;
       this.references = references;
    }
   
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public Duration getDuration() {
        return this.duration;
    }
    
    public void setDuration(Duration duration) {
        this.duration = duration;
    }
    public EducationalLevel getEducationalLevel() {
        return this.educationalLevel;
    }
    
    public void setEducationalLevel(EducationalLevel educationalLevel) {
        this.educationalLevel = educationalLevel;
    }
    public Fields getFields() {
        return this.fields;
    }
    
    public void setFields(Fields fields) {
        this.fields = fields;
    }
    public Payment getPayment() {
        return this.payment;
    }
    
    public void setPayment(Payment payment) {
        this.payment = payment;
    }
    public Qualification getQualification() {
        return this.qualification;
    }
    
    public void setQualification(Qualification qualification) {
        this.qualification = qualification;
    }
    public University getUniversity() {
        return this.university;
    }
    
    public void setUniversity(University university) {
        this.university = university;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTpNo() {
        return this.tpNo;
    }
    
    public void setTpNo(String tpNo) {
        this.tpNo = tpNo;
    }
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDor() {
        return this.dor;
    }
    
    public void setDor(Date dor) {
        this.dor = dor;
    }
    public String getAl() {
        return this.al;
    }
    
    public void setAl(String al) {
        this.al = al;
    }
    public String getOl() {
        return this.ol;
    }
    
    public void setOl(String ol) {
        this.ol = ol;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getFileAtttaches() {
        return this.fileAtttaches;
    }
    
    public void setFileAtttaches(Set fileAtttaches) {
        this.fileAtttaches = fileAtttaches;
    }
    public Set getReferences() {
        return this.references;
    }
    
    public void setReferences(Set references) {
        this.references = references;
    }




}


