package POJOS;
// Generated Jan 26, 2018 9:57:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * University generated by hbm2java
 */
public class University  implements java.io.Serializable {


     private Integer iduni;
     private String name;
     private String degree;
     private String address;
     private String nic;
     private Date startedDate;
     private Set students = new HashSet(0);

    public University() {
    }

	
    public University(String nic) {
        this.nic = nic;
    }
    public University(String name, String degree, String address, String nic, Date startedDate, Set students) {
       this.name = name;
       this.degree = degree;
       this.address = address;
       this.nic = nic;
       this.startedDate = startedDate;
       this.students = students;
    }
   
    public Integer getIduni() {
        return this.iduni;
    }
    
    public void setIduni(Integer iduni) {
        this.iduni = iduni;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public Date getStartedDate() {
        return this.startedDate;
    }
    
    public void setStartedDate(Date startedDate) {
        this.startedDate = startedDate;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


